### ISSUE TITLE
NavigateTo msc2931

### ISSUE THREAD

**Issue by korneyda** [matrix-org/matrix-widget-api#55]
Hello
Tell me, please, what is the status of navigateTo? 
* @deprecated This currently relies on an unstable MSC (MSC2931).

Can I use it in the prod?

**Comment by turt2live** [comment]
You can, though it might get renamed without warning. 

For further support, please visit [#matrix-widget-api:matrix.org](https://matrix.to/#/#matrix-widget-api:matrix.org) on Matrix.
